### ISSUE TITLE
Maquettage - Destination Page (Desktop)

### ISSUE THREAD

**Issue by YounesBousfiha** [Coderyounes/Brief-3-VisitMorocco#11]
@yasser-aboufaris on utilisant Figma Cree une maquette figma pour la page destination, utilisé frame 1280px.

**veuillez de ajouter le lien figma **

**Comment by yasser-aboufaris** [comment]
Voici mon design : https://www.figma.com/design/SwX0oZFY5EBosi1Vgj4MGk/yasser-part?node-id=3-189&t=yat2r40pYgT3WLEa-1

**Comment by YounesBousfiha** [comment]
Merci
