### ISSUE TITLE
Maquettage- FAQ (Desktop)

### ISSUE THREAD

**Issue by YounesBousfiha** [Coderyounes/Brief-3-VisitMorocco#13]
@elmhmmd on utilisant Figma Cree une maquette figma pour la page d'accueill, utilisé frame 1280px.

**veuillez de ajouter le lien figma **

**Comment by elmhmmd** [comment]
https://www.figma.com/design/ZWwKxSXfpN0tjx4mPiMTa5/FAQ-Page?node-id=0-1&node-type=canvas&t=dbyLt0LrwodtsmhI-0
