### ISSUE TITLE
Maquettage - Gastronomie Page (Mobile)

### ISSUE THREAD

**Issue by YounesBousfiha** [Coderyounes/Brief-3-VisitMorocco#16]
@asma828 on utilisant Figma Cree une maquette figma pour la page gastronomie, utilisé frame 412px.

**veuillez de ajouter le lien figma **

**Comment by asma828** [comment]
https://www.figma.com/design/4M4vj78YGvGPvo9Z5JLrG7/Untitled?node-id=0-1&node-type=canvas&t=R1GxWhfMkSr1Q9dX-0
