### ISSUE TITLE
Maquettage- FAQ (Mobile)

### ISSUE THREAD

**Issue by YounesBousfiha** [Coderyounes/Brief-3-VisitMorocco#17]
@elmhmmd on utilisant Figma Cree une maquette figma pour la page FAQ, utilisé frame 412px.

**veuillez de ajouter le lien figma **

**Comment by elmhmmd** [comment]
https://www.figma.com/design/ZWwKxSXfpN0tjx4mPiMTa5/Untitled?node-id=0-1&t=5U3mhnA7Kxrjy4tU-1
