### ISSUE TITLE
WireFrame - Destination Page (Desktop & Mobile)

### ISSUE THREAD

**Issue by YounesBousfiha** [Coderyounes/Brief-3-VisitMorocco#8]
@taouamwalideddine on utilisant Figma Cree Wireframe low-fidelity using figma .

pour Desktop utilise 1280px
Pour Mobile Utilise 412px(Android Compact)

** Veuillez d'ajouter votre lien Ici s'il voud plait **

**Comment by taouamwalideddine** [comment]
voici le lien de le WireFrame low-fidelity utilisant figma.

https://www.figma.com/design/vBjPX2Xhig7n19dZ0PnFvF/Brief-3?node-id=6-2&t=T4Wxqx05cChyiUFv-1
